spring:
  application:
    name: TryApiH2
  datasource:
    url: jdbc:h2:file:./data/mydatabase;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      platform: h2
  h2:
    console:
      enabled: true
      path: /api/h2-console
      settings:
        web-allow-others: true
        trace: false
        web-admin-password: password
    web:
      allow-others: true
  cloud:
    compatibility-verifier:
      enabled: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

server:
  port: 8080
  servlet:
    context-path: /api

currency-service:
  url: localhost:8080/api/currency
  cache:
    ttl: 3600

logging:
  level:
    root: INFO
    com.ratesandtarifs: DEBUG
    org.hibernate.SQL: DEBUG